# Generated by Django 4.2.1 on 2023-05-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calorie', models.IntegerField(default=0)),
                ('BMI_RANGE', models.IntegerField(default=0)),
            ],
        ),
    ]
