# Generated by Django 4.2.1 on 2023-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foods',
            old_name='BMI_RANGE',
            new_name='bmi_end',
        ),
        migrations.AddField(
            model_name='foods',
            name='bmi_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foods',
            name='image',
            field=models.ImageField(default=1, upload_to='food/'),
            preserve_default=False,
        ),
    ]
