# Generated by Django 4.2.1 on 2023-05-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_rename_bmi_range_foods_bmi_end_foods_bmi_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
